version: '3'
services:
  library-db:
    image: 'postgres:alpine'
    container_name: library-db
    volumes:
      - library-data:/var/lib/postgresql/data
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5432:5432'
    networks:
      - library-network
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library

  library-backend:
    build: ./backend
    container_name: library-backend
    environment:
      - DB_HOST=library-db
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
    ports:
      - 8080:8080
    networks:
      - library-network

  library-frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - 3000:80
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  library-data:
