FROM rust:1.60-slim-buster

# Copy the manifests
COPY ./Cargo.lock .
COPY ./Cargo.toml .

# Build a dummy file to cache dependencies
RUN mkdir src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release
RUN rm src/main.rs
RUN rmdir src

# Now that the dependency is built, copy the actual source code
COPY . .
RUN touch src/main.rs

# Build for release.
RUN cargo build --release

# Run the app
CMD ["./target/release/library-backend"]
